name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8  # Use the same Python version as in your environment.yml

    - name: Remove existing environment
      run: |
        conda env remove -n alfred || echo "Environment alfred does not exist"

    - name: Create environment
      run: conda env create -f gotham.yml

    - name: Update environment
      run: conda env update --file gotham.yml --prune

    - name: Run tests
      run: |
        conda run -n alfred python -m unittest discover
